<Project Sdk="Aspire.AppHost.Sdk/13.1.0">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <UserSecretsId>3d24b724-71b3-44a3-a7c6-c1d1a08b15aa</UserSecretsId>
  </PropertyGroup>
  
  <ItemGroup>
    <PackageReference Include="Aspire.Hosting.JavaScript" Version="13.1.0" />
    <PackageReference Include="Aspire.Hosting.SqlServer" Version="13.1.0" />
    <PackageReference Include="CommunityToolkit.Aspire.Hosting.JavaScript.Extensions" Version="13.1.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Services\Auth\AuthService\AuthService.csproj" />
    <ProjectReference Include="..\Services\ClienteCuenta\ClienteCuentaService\ClienteCuentaService.csproj" />
    <ProjectReference Include="..\Services\Tarjeta\TarjetaService\TarjetaService.csproj" />
    <ProjectReference Include="..\Services\Movimiento\MovimientoService\MovimientoService.csproj" />
    <ProjectReference Include="..\Services\Logging\LoggingService\LoggingService.csproj" />
  </ItemGroup>

</Project>
